### ISSUE TITLE
Minimum set of files

### ISSUE THREAD

**Issue by meerfrau** [GENtle-persons/gentle-m#45]
Is there a set of example files to get started?
```
D: Assigned bmpdir to '/bitmaps/'
E: Could not find bitmap directory expected at '/bitmaps/'.
W: Failed to open marker file on '/marker.txt'
I: Expecting database on '/home/papa/local.db'
I: Expecting database on '/blank.db'
```
Empty files don't make it!

**Comment by smoe** [comment]
This does not look healthy, indeed. I know GENtle to have some problem to find its whereabouts, which is why I once introduced those messages to the console, I admittedly still need to make up my mind about what to do about it. Have you compiled the software yourself? Or is this already part of the Debian package? What is the operating system you are are running GENtle on?

I agree that we need some example material.

**Comment by meerfrau** [comment]
Compiled from source at ArchLinux (without a flaw!).

GENtle is at at /usr/bin – would prefer to have the bitmaps at /usr/share

**Comment by smoe** [comment]
The transition from wxWidgets 2 to wxWidgets 3 has a series of subtle side-effects that we are admittedly a bit slow to address. As a quick hack please try starting ./GENtle in the build directory - this finds directories when compiling in a conda environment under macOS.

**Comment by meerfrau** [comment]
Do you have a marker.txt and local.db for me? I cannot know what to put in there.

**Comment by smoe** [comment]
The marker.txt file is distributed with the source tree at https://github.com/GENtle-persons/gentle-m/blob/main/marker.txt and local.db will be created where you started the application or your home directory - where did you start it? And how did you start it? Via the start menu? Or by typing the application's name into the command line?

**Comment by smoe** [comment]
I have not toyed too much with the database management, but try File -> Open to create a new database in a directory to which you have write access.

**Comment by meerfrau** [comment]
`GENTLE_HOMEDIR=/usr/share/gentle GENtle` is working well. The patch, too. Thanks!

**Comment by smoe** [comment]
I am (slowly) working myself through the [Manual](https://github.com/GENtle-persons/gentle-m/blob/main/docs/manual.adoc) that we now have formatted in asciidoc. I tend to think that this solves the issue of missing examples - you just download the sequence from a public database - with the browser or via the command line.
